<a href="https://colab.research.google.com/github/CKDabral/M-L-Exercise/blob/master/Chanderkant_Dabral_asg2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Batch Splitting
Given a numpy array $x$ of shape (samples, features) and parameter $m$ - batch size. Randomly shuffle $x$ and split it into batches of size $m$. The last batch may contain less than $m$ samples. Return the batches in a list.

In [17]:
### Your Code Here
import numpy as np

def shuffle(x):
  a=np.copy(x)
  np.random.shuffle(a)
  return a

def batch(x,m):
  temp=np.array(shuffle(x))
  batches=[]
  j=0
  if len(temp%m==0):
    size=(len(x)//m)
  else:
    size=(len(x)//m)+1
  for i in range(size):
    batches.append(np.array(temp[j:j+m]))
    j=j+m
  return batches
x=np.arange(20).reshape(4,5)
batch(x,2)
  

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9]])]

### Remove Outliers
Given a numpy array $x$ of shape (samples, features) and parameter $threshold$, standardize the dataset first. Remove outliers from the dataset (all points which are more than $threshold$ number of standard deviations away from mean) And return this processed dataset.

In [23]:
### Your Code Here
def remove_outliers(x,threshold):
  samples,features=x.shape
  mean_x=np.mean(x,axis=0)
  std_x=np.std(x,axis=0)
  standard_x=(x-mean_x)/std_x
  print(x,standard_x,sep='\n')
  print('Before X',x)
  for i in range(samples):
    for j in range(features):
      if x[i][j]>threshold:
        x[i][j]=mean_x[j]
  print('After x',x)
x=np.arange(50).reshape(5,10)
remove_outliers(x,4)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[-1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356
  -1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678
  -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678  0.70710678  0.70710678  0.70710678
   0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
   1.41421356  1.41421356  1.41421356  1.41421356]]
Before X [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
After x [[ 0  1  2  3  4 25 26 27 28 29]


### One-hot encoding
Given a list of strings $y$, with output samples. For eg., ['cat', 'dog', 'cat', 'mouse', ...]. One-hot encode this list and return the new output as a numpy array $Y_{oh}$

In [40]:
### Your Code Here
def onehot(y):
  Nclass=len(set(y))
  array=np.array(y)
  unq_lst=np.unique(array)
  Ny=len(unq_lst)
  encd_out=np.zeros((Ny,Ny))
  for i in range(Ny):
    encd_out[i,i]=1
  print(encd_out,Ny)
  Yo=[]
  for i in y:
    j=list(unq_lst).index(i)
    Yo.append(encd_out[j])
  return Yo
onehot(['cat', 'dog', 'cat', 'mouse'])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 3


[array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 0., 1.])]

### Generate Data, random points in circle
You need to write a function that does the following. <br>
Given a tuple $t$ denoting coordinates of the center of a circle and float $r$ denoting radius. <br>
Generate a random point that lies within the circle and return it. Try to only the simple np.random.random function.

In [0]:
### Your Code Here

def circle(t,radius):
  x,y=t
  x_range=x+radius-(x-radius)
  x_par=x-radius
  y_range=y+radius-(y-radius)
  y_par=y-radius
  x1=x_range*np.random.random()+x_par
  y1=y_range*np.random.random()+y_par
  return x1,y1

### Rank array
Rank the items in a multidimensional array 'arr'. <br>
Define the rank of an item as its index in the sorted list of all items in 'arr' (starting from 0). <br>
          Eg., consider arr = [0, 6, 14, 12, 11] <br>
                  arr_sorted = [0, 6, 11, 12, 14] <br>
                  So rank of 0 -> 0; 6->1; 11->2, 12->3, 14->4 <br>
                  rankArray returns a list where each element is replaced by its rank <br>
                  rankArray(arr) -> [0, 1, 4, 3, 2] <br>

Write a function which takes as input a numpy array of shape (m, n) and returns a numpy array of shape(m,n) which contains the ranks corresponding to each element. The rank of an element in a multidimensional array $a$ is the same as its rank in the 1d array obtained by flattening $a$

In [64]:
def rank(a):
  flat_arr=a.flatten()
  sort_arr=np.sort(flat_arr)
  lst=list(sort_arr)
  for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      a[i,j]=lst.index(a[i,j])
  return a
rank(np.random.randint(10,100,12).reshape(3,4))

array([[ 1, 10,  6,  9],
       [ 3,  4,  8,  0],
       [ 2,  5, 11,  7]])